name: Feature Request
description: Open an issue to ask for a GenHotkeys feature to be implemented.
title: "Your feature request title here"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please make sure you fill in every gaps with as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Write a detailed description telling us what the feature you want to be implemented in the GenHotkeys.
    validations:
      required: true
